name: Jay Kennedy
favicon: null
layout_spectrum: 0.00097
typography_spectrum: 0.59445
title: The Convocant
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#f6f1ee'
    - '#22231d'
    - '#9bbee4'
    - '#a0857e'
    - '#6c6b71'
  brandStrength: 1
  lightness: 0
  saturation: 1
  rhythmicContrast: 0
purpose: []
