name: Jay Kennedy
favicon: null
layout_spectrum: 0.29463
typography_spectrum: 0.8012345288880169
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#a49a90'
    - '#c2baaf'
    - '#76685d'
    - '#463c33'
    - '#171008'
  brandStrength: 1
  lightness: 0.8125
  saturation: 0.875
  rhythmicContrast: 0.25
purpose: []
